/**
 * Common given names (folded: lowercase ASCII, accents removed), used by the
 * Blind-CIM identity guard (shared/blind-guard.ts) to recognise a person in
 * a staffing fact: a capitalised word that is a known given name starts a
 * person's name ("Carlos Reyes (12)", "Maria Teller (bookkeeper)").
 *
 * Wide, multicultural coverage matters more than completeness: a name that
 * is missing here is still caught when it stands alone as a list entry
 * ("Xiaoling Wu (12)"). Given names that are also everyday words ("Grace",
 * "Will", "Summer") are handled as ambiguous by the guard, not removed.
 * Embedded in code (no runtime files).
 */
const NAMES = `
aaliyah aaron abby abdul abdullah abel abigail abraham ada adam addison adeel adele adeline adil aditi aditya adnan adrian adriana adrienne agatha agnes ahmad ahmed aidan aiden aileen aimee aisha akash akira al alain alan alana alastair albert alberta alberto alec alejandra alejandro aleksandr aleksandra alessandra alessandro alex alexa alexander alexandra alexandre alexandria alexis alfonso alfred alfredo ali alice alicia alina alisha alison alistair allan allen allison alma alonso alvaro alvin alya alyssa amal amanda amandeep amar amber amelia amelie amin amina amir amit amos amrit amy ana anabel anand ananya anastasia anders andre andrea andreas andrei andres andrew andy aneesh angel angela angelica angelina angelo angie anil anika anita anja anjali ann anna annabelle anne annette annie anoop anthony antoine anton antonia antonio anu anuj anwar april arash archie ari ariana ariel arjun arlene armand armando arnav arnold aron arthur arturo arun arvind asha ashish ashley ashok ashton asif astrid audrey august augustin aurelie austin ava avery avi axel ayesha ayla aziz
barbara barry bart basil beatrice beatriz becky belinda bella ben benedict benjamin benoit bernadette bernard bernardo bernie beth bethany betty beverly bharat bianca bilal bill billy bjorn blair blake bob bobby bogdan bonnie boris brad bradley brady brandon brandy breanna brenda brendan brent brett brian briana bridget brigitte britney brittany brody brooke bruce bruno bryan bryce bryson byron
caitlin caleb calvin camila cameron camille candace cara carina carl carla carlo carlos carly carmen carol carole caroline carolyn carrie carson carter casey cassandra cassidy catalina catarina caterina catherine cathy cecilia cedric celeste celine cesar chad chandra chantal charlene charles charlie charlotte chase chelsea cheng cheryl chetan chiara chloe chris christian christina christine christophe christopher chuck cindy claire clara clarence claude claudia claudio clayton clement cliff clifford clint clinton cody colby cole colette colin colleen collin connor conor conrad constance cora corey corinne cory courtney craig cristian cristina crystal curtis cynthia cyril
daisy dakota dale dalia damian damien damon dan dana daniel daniela daniele danielle danny dante daphne darcy darius darlene darnell darren darryl daryl dave david davide dawn dean deanna debbie deborah debra deepa deepak deirdre delia denis denise dennis derek derrick desiree desmond devin devon dhruv diana diane diego dimitri dina dinesh dino dmitri dmitry dolores dominic dominique don donald donna dora doreen doris dorothy doug douglas drew duane duncan dustin dwayne dylan
earl ed eddie edgar edith edmond edmund eduardo edward edwin eileen elaine elena eleanor eli elias elijah elisa elisabeth elise eliza elizabeth ella ellen ellie elliot elliott eloise elsa elsie emad emanuel emil emilia emilie emilio emily emma emmanuel emmett enrique eric erica erik erika erin ernest ernesto esme esperanza esteban estelle esther ethan etienne eugene eva evan evangeline evelyn everett ezra
fabian fabio fadi faisal farah farhan farid fatima fatma faye federico felicia felipe felix fernanda fernando fiona florence florian floyd frances francesca francesco francine francis francisco franco francois francoise frank frankie franz fraser fred freddie frederic frederick freya fritz
gabriel gabriela gabrielle gail gareth garrett garry gary gaurav gavin gemma gene genevieve geoff geoffrey george georgia georgina gerald geraldine gerard gerardo gerhard gilbert gilles gillian gina ginette giorgio giovanni gisele giulia giuseppe gladys glen glenda glenn gloria gordon grace graham grant greg gregory greta guillaume guillermo gurdeep gurpreet gustavo guy gwen gwendolyn
hailey haley hamid hamza hana hannah hans harjit harold harper harpreet harriet harrison harry harvey hassan heather hector heidi helen helena helene henri henrietta henry herbert herman hilary hilda hiroshi holly hope howard hugh hugo hunter hussein
ian ibrahim ida ignacio igor ilya imran ines inga ingrid irene iris irina isaac isabel isabella isabelle isaiah ishaan isla ismail ivan ivy
jack jackie jackson jacob jacqueline jacques jade jaime jake jamal james jamie jan jana jane janet janice janine jared jasmin jasmine jason jasper javier jay jayden jean jeanette jeanne jeff jeffrey jenna jennifer jenny jeremiah jeremy jerome jerry jesse jessica jessie jesus jill jim jimmy jin jing joan joanna joanne joao jocelyn jodi jody joe joel joey johan johanna john johnny jon jonah jonas jonathan jordan jorge jose josee josef joseph josephine josh joshua josiah joy joyce juan juanita judith judy jules julia julian juliana julie julien juliet julio june justin justine
kai kamal kamala kara karan karen kari karim karin karina karl karla karthik kasia kate katelyn katherine kathleen kathryn kathy katie katrina kavita kay kayla keira keith kelly kelsey ken kendra kenji kenneth kenny kent kerry kevin khalid kim kimberly kirk kirsten klaus krista kristen kristin kristina krystal kumar kurt kyle kylie
lachlan lakshmi lana lance lara larry lars laura laurel lauren laurence laurent laurie lawrence layla leah lee leila lena leo leon leonard leonardo leslie lester levi lewis liam lila lillian lily lina linda lindsay lindsey lionel lisa liz liza lloyd logan lois lorena lorenzo loretta lori lorna lorraine louis louisa louise luc luca lucas lucia luciana lucie lucy luis luisa luke luz lydia lyle lynda lynn lynne
mackenzie madeleine madeline madison magda magdalena maggie mahmoud maia malcolm malik mandeep mandy manish manoj manon manuel mara marc marcel marcela marcia marco marcos marcus margaret margarita margot maria mariam marian mariana marianne marie marilyn marina mario marion marisa marissa marius marjorie mark marko marlene marshall marta martha martin martina marty marvin mary maryam mason mateo mathew mathieu matilda matteo matthew matthias maureen maurice mauricio max maxime maxwell maya megan meghan mehdi mehmet melanie melissa melody mercedes meredith mia micah michael michaela michel michele michelle miguel mihai mikayla mike mikhail mila milan miles milo mina minh miranda miriam misha mitchell mohamed mohammad mohammed mohan moira molly mona monica monique morgan moses muhammad murray mustafa
nadia nadine nancy naomi narinder natalia natalie natasha nathalie nathan nathaniel naveen navdeep navjot neha neil nelson nicholas nick nicki nicola nicolas nicole nigel nikhil niklas nikki nikolai nils nina nisha nitin noah noel noelle nora norma norman
octavia olga oliver olivia omar oscar owen
pablo paige pamela paolo parker pascal pat patricia patrick patti paul paula pauline pavel pedro peggy penelope penny percy peter petra phil philip philippe phillip phoebe pierre pieter piotr pooja prakash pranav prashant pratik preeti preston priscilla priya priyanka
qasim quentin quinn
rachel radu rafael raffaele raghav rahul raj rajan rajesh rajiv ralph ramesh ramon rana randall randy raphael rashid raul ravi ravinder ray raymond reba rebecca reed reggie regina reginald rehan reid rekha remy rene renee reza rhonda ricardo richard rick ricky riley rita rob robert roberta roberto robin rocco rod rodney rodrigo roger rohan rohit roland rolando roman ron ronald ronnie rory rosa rosalie rosario rose rosemary ross roxanne roy ruben ruby rudy rupert russell ruth ryan
sabrina sadie sahil salim sally salma salvador salvatore sam samantha sameer samir samira samuel sana sandeep sandip sandra sandro sandy sanjay sanjeev santiago santosh sara sarah sasha satish saul savannah scott sean sebastian sergei sergey sergio seth shabnam shane shannon sharon shauna shawn shawna sheena sheila shelby shelley sherry shirley shivani shreya shruti sidney silvia simon simone simran siobhan sofia sonia sonja sophia sophie spencer stacey stacy stan stanley stefan stefania stefano steffi stella stephan stephane stephanie stephen steve steven stuart sue sukhdeep sultan sumit sunil sunita suresh susan susanne suzanne sven svetlana sylvain sylvia sylvie
tamara tammy tania tanya tara tariq tatiana taylor ted teresa terrence terri terry tess tessa thanh theo theodore theresa thierry thomas tiffany tim timothy tina tobias toby todd tom tomas tommy toni tony tracey tracy travis trevor trish troy tyler tyson
uma umar uri ursula usman
valentina valerie vanessa varun vasile veronica veronique vicki vicky victor victoria vijay vikas vikram vincent vinod violet virginia vishal vivek vivian viviane vladimir
wade walter wanda warren wayne wei wendy wesley whitney will william willie wilson winston wolfgang
xavier xin
yan yang yasmin yasmine yolanda yosef youssef yuki yuri yusuf yves yvette yvonne
zach zachary zain zainab zara zeynep zoe zoey zofia
huong linh ngoc phuong thao trang tuan quang hoa hanh thuy
ming xiao hui jian mei ying feng chen
hyun kyung joon
aarav anushka gurleen harleen jaspreet kiran manpreet parveen rupinder sukhwinder tejinder
yasir zubair tahir nasir shahid farooq irfan junaid kashif naveed rizwan saad saqib usama waqas
chukwuma chidi emeka ngozi oluwaseun olumide adebayo ayodele kwame kofi ama abena yaw amara nnamdi
`;

export const GIVEN_NAMES = new Set(NAMES.split(/\s+/).filter(Boolean));
