import type { Deal, Document, Task, InterviewSession, ExtractedInfo, Discrepancy } from "@shared/schema";
import { CIM_SECTIONS } from "@shared/schema";

// =====================
// Types
// =====================

export interface KnowledgeBase {
  // Business identity
  business: {
    name: string;
    industry: string;
    subIndustry: string | null;
    description: string | null;
    location: LocationContext | null;
  };

  // Everything we know, organized by CIM section
  sectionCoverage: SectionCoverage[];

  // Industry-specific context (populated once industry + location are known)
  industryContext: IndustryContext | null;

  // What the seller told us in the questionnaire before the interview
  questionnaireData: Record<string, unknown> | null;

  // Operational systems the seller uses (guides retrieval instructions)
  operationalSystems: OperationalSystems | null;

  // Documents uploaded for this deal
  documents: DocumentSummary[];

  // Outstanding tasks (follow-ups, skipped questions, doc requests)
  outstandingTasks: TaskSummary[];

  // Prior interview sessions (if resuming)
  priorSessionSummary: PriorSessionSummary | null;

  // Raw extracted info (the flat key-value store from the schema)
  extractedInfo: Partial<ExtractedInfo>;

  // Publicly scraped data — UNVERIFIED, must be confirmed with seller during interview
  scrapedData: Record<string, string> | null;
  scrapeSource: "website" | "internet_search" | "website_and_internet" | null;
}

export interface LocationContext {
  country: string | null;
  stateProvince: string | null;
  municipality: string | null;
  raw: string | null; // The original location string if we can't parse it
}

export interface SectionCoverage {
  key: string;
  title: string;
  order: number;
  status: "well_covered" | "partial" | "missing";
  // Which extracted fields map to this section and their current values
  fields: Array<{
    fieldName: string;
    value: string | null;
    confidence: "confirmed" | "inferred" | "approximate" | "unknown";
  }>;
}

export interface IndustryContext {
  industry: string;
  subIndustry: string | null;
  location: LocationContext | null;
  // These are generated by the AI on the first turn once industry is identified.
  // We store them so the system prompt can reference them on subsequent turns.
  industrySpecificAreas: string[];
  regulatoryNotes: string[];
}

export interface OperationalSystems {
  accounting: string | null;
  crm: string | null;
  pos: string | null;
  erp: string | null;
  payroll: string | null;
  other: string[];
}

export interface DocumentSummary {
  id: string;
  name: string;
  category: string;
  subcategory: string | null;
  status: string;
  isProcessed: boolean;
  hasExtractedText: boolean;
  hasExtractedData: boolean;
}

export interface TaskSummary {
  id: string;
  type: string;
  title: string;
  description: string | null;
  relatedField: string | null;
  status: string;
  priority: string;
  aiAttempts: number | null;
  aiExplanation: string | null;
}

export interface PriorSessionSummary {
  sessionId: string;
  questionsAsked: number | null;
  questionsAnswered: number | null;
  questionsSkipped: number | null;
  lastActivityAt: Date;
  status: string;
}

// =====================
// Section-to-field mapping
// =====================

// Maps each CIM section to the extractedInfo fields that populate it.
// This is how we determine coverage per section.
const SECTION_FIELD_MAP: Record<string, string[]> = {
  overview: [
    "businessName", "industry", "companyHistory", "yearsOperating",
    "entityType", "brandIdentity", "missionStatement", "coreValues",
    "ownershipHistory", "industryPerception", "customerPerception", "accolades",
  ],
  strengths: [
    "competitiveAdvantage", "uniqueSellingProposition", "strengths",
  ],
  growth_potential: [
    "growthOpportunities", "expansionPlans",
  ],
  target_market: [
    "targetMarket", "primaryMarket", "secondaryMarket",
    "b2bBreakdown", "customerDemographics", "customerBase",
  ],
  permits_licenses: [
    "permitsLicenses", "complianceRequirements",
  ],
  seasonality: [
    "seasonality", "peakPeriods", "slowPeriods",
  ],
  revenue_sources: [
    "revenueStreams", "keyProducts", "customerConcentration",
    "annualRevenue", "revenueGrowth", "operatingMargins",
  ],
  real_estate: [
    "leaseDetails", "propertyInfo", "realEstateIncluded",
  ],
  employees: [
    "employees", "employeeStructure", "keyEmployees", "ownerInvolvement",
    "managementTeam",
  ],
  operations: [
    "suppliers", "supplyChain", "technologySystems", "operationalSystems",
  ],
  buyer_profile: [
    "idealBuyer",
  ],
  training_support: [
    "trainingSupport", "transitionPlan",
  ],
  reason_for_sale: [
    "reasonForSale",
  ],
  financials: [
    "annualRevenue", "revenueGrowth", "operatingMargins",
    "workingCapital", "debt",
  ],
  asking_price: [
    "askingPrice", "saleType", "assetsIncluded", "inventory",
  ],
};

// =====================
// Knowledge base assembly
// =====================

export function assembleKnowledgeBase(
  deal: Deal,
  documents: Document[],
  tasks: Task[],
  latestSession: InterviewSession | null,
  resolvedDiscrepancies: Discrepancy[] = [],
): KnowledgeBase {
  const baseExtractedInfo = (deal.extractedInfo as Partial<ExtractedInfo>) || {};
  const questionnaireData = deal.questionnaireData as Record<string, unknown> | null;

  // Overlay resolved discrepancy values — corrected values win over raw extractedInfo
  // so the interview agent never re-asks for or builds on stale numbers the broker
  // already reconciled against uploaded documents.
  const extractedInfo: Partial<ExtractedInfo> = { ...baseExtractedInfo };
  for (const d of resolvedDiscrepancies) {
    if (d.resolvedValue && d.field) {
      (extractedInfo as Record<string, unknown>)[d.field] = d.resolvedValue;
    }
  }

  return {
    business: {
      name: deal.businessName,
      industry: deal.industry,
      subIndustry: deal.subIndustry,
      description: deal.description,
      location: parseLocation(deal, questionnaireData),
    },
    sectionCoverage: buildSectionCoverage(extractedInfo),
    industryContext: null, // Set by the AI on first turn, stored on session
    questionnaireData,
    operationalSystems: parseOperationalSystems(deal),
    documents: documents.map(summarizeDocument),
    outstandingTasks: tasks
      .filter((t) => t.status === "pending" || t.status === "in_progress")
      .map(summarizeTask),
    priorSessionSummary: latestSession ? summarizeSession(latestSession) : null,
    extractedInfo,
    scrapedData: (deal.scrapedData as Record<string, string> | null) || null,
    scrapeSource: (deal.scrapeSource as "website" | "internet_search" | "website_and_internet" | null) || null,
  };
}

// =====================
// Rendering for system prompt injection
// =====================

export function renderKnowledgeBaseForPrompt(kb: KnowledgeBase): string {
  const parts: string[] = [];

  // Scraped data — shown first so the agent is primed to verify it
  if (kb.scrapedData && Object.keys(kb.scrapedData).length > 0) {
    const sourceLabel = kb.scrapeSource === "website"
      ? "the business's public website"
      : kb.scrapeSource === "website_and_internet"
        ? "the business's public website and public internet search results (reviews, directories, news, social media)"
        : "public internet search results (directories, news, review sites)";

    parts.push(`## ⚠️ PUBLICLY FOUND DATA — UNVERIFIED`);
    parts.push(`The following was found on ${sourceLabel} BEFORE the interview. It has NOT been confirmed by the seller.`);
    parts.push(``);
    parts.push(`YOUR JOB: Verify these facts naturally during the interview. Do not list them all at once.`);
    parts.push(`Weave verification into conversation: "I noticed on your website that you've been in business since 2010 — is that right?" or "I saw online that you have two locations — can you confirm that?"`);
    parts.push(`When the seller confirms → extract the field as confirmed. When they correct → use their version. When they say it's wrong → note it and use their answer.`);
    parts.push(``);
    for (const [key, value] of Object.entries(kb.scrapedData)) {
      parts.push(`- ${key}: "${value}"  [UNVERIFIED — confirm with seller]`);
    }
    parts.push(``);
  }

  // Business identity
  parts.push(`## Business Profile`);
  parts.push(`- Name: ${kb.business.name}`);
  parts.push(`- Industry: ${kb.business.industry}${kb.business.subIndustry ? ` (${kb.business.subIndustry})` : ""}`);
  if (kb.business.description) {
    parts.push(`- Description: ${kb.business.description}`);
  }
  if (kb.business.location) {
    const loc = kb.business.location;
    const locParts = [loc.municipality, loc.stateProvince, loc.country].filter(Boolean);
    if (locParts.length > 0) {
      parts.push(`- Location: ${locParts.join(", ")}`);
    } else if (loc.raw) {
      parts.push(`- Location: ${loc.raw}`);
    }
  }

  // Questionnaire data (what the seller already provided before the interview)
  if (kb.questionnaireData && Object.keys(kb.questionnaireData).length > 0) {
    parts.push("");
    parts.push(`## Pre-Interview Questionnaire Answers`);
    parts.push(`The seller already provided these answers in the intake questionnaire. DO NOT re-ask for this information — confirm it or build on it.`);
    for (const [key, value] of Object.entries(kb.questionnaireData)) {
      if (value !== null && value !== undefined && value !== "") {
        parts.push(`- ${key}: ${typeof value === "object" ? JSON.stringify(value) : String(value)}`);
      }
    }
  }

  // Operational systems (for retrieval instructions)
  if (kb.operationalSystems) {
    const systems = kb.operationalSystems;
    const knownSystems: string[] = [];
    if (systems.accounting) knownSystems.push(`Accounting: ${systems.accounting}`);
    if (systems.crm) knownSystems.push(`CRM: ${systems.crm}`);
    if (systems.pos) knownSystems.push(`POS: ${systems.pos}`);
    if (systems.erp) knownSystems.push(`ERP: ${systems.erp}`);
    if (systems.payroll) knownSystems.push(`Payroll: ${systems.payroll}`);
    if (systems.other.length > 0) knownSystems.push(`Other: ${systems.other.join(", ")}`);

    if (knownSystems.length > 0) {
      parts.push("");
      parts.push(`## Seller's Operational Systems`);
      parts.push(`Use these to give specific retrieval instructions when the seller doesn't know where to find information.`);
      knownSystems.forEach((s) => parts.push(`- ${s}`));
    }
  }

  // Section coverage
  parts.push("");
  parts.push(`## CIM Section Coverage`);
  parts.push(`This shows what information we have for each CIM section. Focus on "missing" and "partial" sections.`);

  for (const section of kb.sectionCoverage) {
    const icon = section.status === "well_covered" ? "[COVERED]"
      : section.status === "partial" ? "[PARTIAL]"
      : "[MISSING]";

    parts.push(`\n### ${icon} ${section.title}`);

    if (section.fields.length === 0) {
      parts.push(`  No data captured yet.`);
      continue;
    }

    for (const field of section.fields) {
      if (field.value) {
        parts.push(`  - ${field.fieldName}: ${field.value} (${field.confidence})`);
      } else {
        parts.push(`  - ${field.fieldName}: NOT YET CAPTURED`);
      }
    }
  }

  // Documents
  if (kb.documents.length > 0) {
    parts.push("");
    parts.push(`## Uploaded Documents`);
    parts.push(`These documents have been uploaded for this deal. Do NOT ask the seller to upload documents they've already provided.`);
    for (const doc of kb.documents) {
      const status = doc.isProcessed ? "processed" : doc.status;
      parts.push(`- ${doc.name} (${doc.category}${doc.subcategory ? `/${doc.subcategory}` : ""}) — ${status}`);
    }
  }

  // Outstanding tasks
  if (kb.outstandingTasks.length > 0) {
    parts.push("");
    parts.push(`## Outstanding Tasks & Deferred Questions`);
    parts.push(`These items were flagged in previous sessions. Consider addressing them when the moment is right.`);
    for (const task of kb.outstandingTasks) {
      parts.push(`- [${task.type}] ${task.title}: ${task.description || "No details"}${task.relatedField ? ` (field: ${task.relatedField})` : ""}`);
      if (task.aiExplanation) {
        parts.push(`  Context: ${task.aiExplanation}`);
      }
    }
  }

  // Industry-specific context (set after first turn identifies industry)
  if (kb.industryContext) {
    parts.push("");
    parts.push(`## Industry-Specific Intelligence`);
    parts.push(`Industry: ${kb.industryContext.industry}${kb.industryContext.subIndustry ? ` — ${kb.industryContext.subIndustry}` : ""}`);

    if (kb.industryContext.industrySpecificAreas.length > 0) {
      parts.push(`\nKey industry-specific areas to cover for this business:`);
      kb.industryContext.industrySpecificAreas.forEach((area) => parts.push(`- ${area}`));
    }

    if (kb.industryContext.regulatoryNotes.length > 0) {
      parts.push(`\nLocation-specific regulatory requirements:`);
      kb.industryContext.regulatoryNotes.forEach((note) => parts.push(`- ${note}`));
    }
  }

  // Prior session context
  if (kb.priorSessionSummary) {
    const ps = kb.priorSessionSummary;
    parts.push("");
    parts.push(`## Prior Interview Session`);
    parts.push(`A previous interview session exists (status: ${ps.status}).`);
    parts.push(`- Questions asked: ${ps.questionsAsked ?? 0}`);
    parts.push(`- Questions answered: ${ps.questionsAnswered ?? 0}`);
    parts.push(`- Questions skipped: ${ps.questionsSkipped ?? 0}`);
    parts.push(`You are resuming this interview. Review the conversation history and continue from where it left off. Do not repeat questions that were already answered.`);
  }

  return parts.join("\n");
}

// =====================
// Internal helpers
// =====================

function buildSectionCoverage(extractedInfo: Partial<ExtractedInfo>): SectionCoverage[] {
  return CIM_SECTIONS.map((section) => {
    const fieldNames = SECTION_FIELD_MAP[section.key] || [];
    const fields = fieldNames.map((fieldName) => {
      const value = extractedInfo[fieldName as keyof ExtractedInfo] ?? null;
      return {
        fieldName,
        value: value as string | null,
        confidence: (value ? "confirmed" : "unknown") as "confirmed" | "inferred" | "approximate" | "unknown",
      };
    });

    const populatedCount = fields.filter((f) => f.value !== null).length;
    const totalCount = fields.length;

    let status: SectionCoverage["status"];
    if (totalCount === 0 || populatedCount === 0) {
      status = "missing";
    } else if (populatedCount >= totalCount * 0.6) {
      status = "well_covered";
    } else {
      status = "partial";
    }

    return {
      key: section.key,
      title: section.title,
      order: section.order,
      status,
      fields,
    };
  });
}

function parseLocation(deal: Deal, questionnaireData: Record<string, unknown> | null): LocationContext | null {
  // Try to extract location from questionnaire data first
  if (questionnaireData) {
    const country = questionnaireData["Country"] || questionnaireData["country"];
    const state = questionnaireData["State"] || questionnaireData["state"]
      || questionnaireData["Province"] || questionnaireData["province"]
      || questionnaireData["State/Province"] || questionnaireData["stateProvince"];
    const city = questionnaireData["City"] || questionnaireData["city"]
      || questionnaireData["Municipality"] || questionnaireData["municipality"];
    const location = questionnaireData["Location"] || questionnaireData["location"];

    if (country || state || city) {
      return {
        country: country ? String(country) : null,
        stateProvince: state ? String(state) : null,
        municipality: city ? String(city) : null,
        raw: null,
      };
    }

    if (location) {
      return { country: null, stateProvince: null, municipality: null, raw: String(location) };
    }
  }

  // Try extractedInfo
  const extractedInfo = deal.extractedInfo as Partial<ExtractedInfo> | null;
  if (extractedInfo?.locations) {
    return { country: null, stateProvince: null, municipality: null, raw: extractedInfo.locations };
  }

  return null;
}

function parseOperationalSystems(deal: Deal): OperationalSystems | null {
  const systems = deal.operationalSystems as Record<string, unknown> | null;
  if (!systems) return null;

  return {
    accounting: systems.accounting ? String(systems.accounting) : null,
    crm: systems.crm ? String(systems.crm) : null,
    pos: systems.pos ? String(systems.pos) : null,
    erp: systems.erp ? String(systems.erp) : null,
    payroll: systems.payroll ? String(systems.payroll) : null,
    other: Array.isArray(systems.other) ? systems.other.map(String) : [],
  };
}

function summarizeDocument(doc: Document): DocumentSummary {
  return {
    id: doc.id,
    name: doc.name,
    category: doc.category,
    subcategory: doc.subcategory,
    status: doc.status,
    isProcessed: doc.isProcessed ?? false,
    hasExtractedText: !!doc.extractedText,
    hasExtractedData: !!doc.extractedData,
  };
}

function summarizeTask(task: Task): TaskSummary {
  return {
    id: task.id,
    type: task.type,
    title: task.title,
    description: task.description,
    relatedField: task.relatedField,
    status: task.status,
    priority: task.priority,
    aiAttempts: task.aiAttempts,
    aiExplanation: task.aiExplanation,
  };
}

function summarizeSession(session: InterviewSession): PriorSessionSummary {
  return {
    sessionId: session.id,
    questionsAsked: session.questionsAsked,
    questionsAnswered: session.questionsAnswered,
    questionsSkipped: session.questionsSkipped,
    lastActivityAt: session.lastActivityAt,
    status: session.status,
  };
}
